export const BEFORE_SIGNUP = 'BEFORE_SIGNUP'
export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'

export const SIGN_OUT = 'SIGN_OUT'

export const BEFORE_SUPERADMIN ='BEFORE_SUPERADMIN'
export const AFTER_SUPERADMIN = 'AFTER_SIGNUPADMIN'
export const SUPERADMIN_ERROR = 'SUPERADMIN_ERROR'

export const BEFORE_GET_LECTURERS = 'BEFORE_GET_LECTURERS'
export const AFTER_LECTURERS = 'AFTER_LECTURERS'
export const GET_LECTURERS_ERROR = 'GET_LECTURERS_ERROR'

export const AFTER_NEW_SUBJECT = 'AFTER_NEW_SUBJECT'
export const BEFORE_NEW_SUBJECT = 'BEFORE_NEW_SUBJECT'
export const SUBJECT_ERROR = 'SUBJECT_ERROR'

export const BEFORE_SEARCH = 'BEFORE_SEARCH'
export const AFTER_SEARCH = 'AFTER_SEARCH'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const SEARCH_RESET= 'SEAECH_RESET'

export const BEFORE_SUBMIT_UPDATE = 'BEFORE_SUBMIT_UPDATE'
export const AFTER_SUBMIT_UPDATE= 'AFTER_SUBMIT_UPDATE'
export const SUBMIT_UPDATE_ERROR= 'SUBMIT_UPDATE_ERROR'
export const SUBMIT_UPDATE_ERROR_RESET = 'SUBMIT_UPDATE_ERROR_RESET'

export const BEFORE_GET_STUDENT ='BEFORE_GET_STUDENT'
export const AFTER_GET_STUDENT = 'AFTER_GET_STUDENT'
export const GET_STUDENT_ERROR = 'GET_STUDENT_ERROR'
export const CLEAR_STUDENT = 'CLEAR_STUDENT'

export const AFTER_GET_SUBJECT = 'AFTER_GET_SUBJECT'
export const BEFORE_GET_SUBJECT = 'BEFORE_GET_SUBJECT'
export const GET_SUBJECT_ERROR = 'GET_SUBJECTT_ERROR'
export const CLEAR_SUBJECT = 'CLEAR_SUBJECT'

export const BEFORE_SUBMIT_RESULT_ADMIN = 'BEFORE_SUBMIT_RESULT_ADMIN'
export const SUBMIT_RESULT_ADMIN_SUCCESS = 'SUBMIT_RESULT_ADMIN_SUCCESS'
export const SUBMIT_RESULT_ADMIN_ERROR = 'SUBMIT_RESULT_ADMIN_ERROR'
export const SUBMIT_RESULT_ADMIN_RESET = 'SUBMIT_RESULT_ADMIN_RESET'


export const BEFORE_GET_RESULT_ADMIN = 'BEFORE_GET_RESULT_ADMIN'
export const GET_RESULT_ADMIN_SUCCESS = 'GET_RESULT_ADMIN_SUCCESS'
export const GET_RESULT_ADMIN_ERROR = 'GET_RESULT_ADMIN_ERROR'
export const GET_RESULT_ADMIN_RESET = 'GET_RESULT_ADMIN_RESET'

export const BEFORE_DELETE_RESULT_ADMIN = 'BEFORE_DELETE_RESULT_ADMIN'
export const DELETE_RESULT_ADMIN_SUCCESS = 'DELETE_RESULT_ADMIN_SUCCESS'
export const DELETE_RESULT_ADMIN_ERROR = 'DELETE_RESULT_ADMIN_ERROR'
export const DELETE_RESULT_ADMIN_RESET = 'DELETE_RESULT_ADMIN_RESET'

export const BEFORE_GET_ACADEMIC_SESSION = 'BEFORE_GET_ACADEMIC_SESSION'
export const GET_ACADEMIC_SESSION_SUCCESS = 'GET_ACADEMIC_SESSION_SUCCESS'
export const GET_ACADEMIC_SESSION_ERROR = 'GET_ACADEMIC_SESSION_ERROR'

export const BEFORE_POST_ACADEMIC_SESSION = 'BEFORE_POST_ACADEMIC_SESSION'
export const POST_ACADEMIC_SESSION_SUCCESS = 'POST_ACADEMIC_SESSION_SUCCESS'
export const POST_ACADEMIC_SESSION_ERROR = 'POST_ACADEMIC_SESSION_ERROR'

export const BEFORE_GET_GROUP = 'BEFORE_GET_GROUP'
export const AFTER_GET_GROUP = 'AFTER_GET_GROUP'
export const GET_GROUP_ERROR = 'GET_GROUP_ERROR'
export const RESET_GET_GROUP = 'RESET_GET_GROUP'

export const BEFORE_GET_RESULT_BY_LECTURER = 'BEFORE_GET_RESULT_BY_LECTURER'
export const AFTER_GET_RESULT_BY_LECTURER = 'AFTER_GET_RESULT_BY_LECTURER'
export const GET_RESULT_BY_LECTURER_ERROR = 'GET_RESULT_BY_LECTURER_ERROR'